import { readYaml, writeMarkdown } from "@aios-celx/artifact-manager";
import { describeExecutionConfig } from "@aios-celx/engine-adapters";
import type { AgentResult } from "@aios-celx/shared";
import { ProjectConfigSchema, normalizeProjectConfig } from "@aios-celx/shared";
import { evaluateGate, getActiveStep } from "@aios-celx/workflow-engine";
import { join } from "node:path";
import type { AgentExecutionContext } from "../context.js";

export async function runDeliveryManager(ctx: AgentExecutionContext): Promise<AgentResult> {
  const active = getActiveStep(ctx.workflow, ctx.state);
  const configPath = join(ctx.projectRoot, ".aios", "config.yaml");
  const raw = await readYaml<unknown>(configPath);
  const projectConfig = normalizeProjectConfig(ProjectConfigSchema.parse(raw));

  const gatePreview = active
    ? await evaluateGate(ctx.projectRoot, active.gate, {
        taskId: ctx.state.currentTaskId ?? undefined,
      })
    : { gateId: "(none)", passed: true, checks: [] };

  const engineForNext = active
    ? describeExecutionConfig(projectConfig, active.agent)
    : describeExecutionConfig(projectConfig, ctx.state.currentAgent);

  const statusPath = "docs/delivery-status.md";
  const summaryPath = "docs/delivery-summary.md";

  const statusBody = `# Delivery status — ${ctx.projectId}

## Operational snapshot

| Field | Value |
|-------|--------|
| Stage | ${ctx.state.stage} |
| Current agent (state) | ${ctx.state.currentAgent} |
| Next gate | ${ctx.state.nextGate || "(none)"} |
| Blocked (flag) | ${ctx.state.blocked ? "yes" : "no"} |
| Requires human approval | ${ctx.state.requiresHumanApproval ? "yes" : "no"} |
| Completed gates | ${ctx.state.completedGates.join(", ") || "(none)"} |

## Memory (Bloco 5.1)

Filtered slices passed to this agent (\`delivery-manager\`): **${ctx.memory.global.length}** global entries, **${ctx.memory.project.length}** project entries.

## Workflow focus

${
  active
    ? `- Active step: **${active.id}** (${active.stage})
- Responsible agent: **${active.agent}**
- Gate to satisfy: **${active.gate}**
- Gate checks (preview): **${gatePreview.passed ? "PASS" : "FAIL"}**`
    : "- No active step — all workflow gates may be approved or workflow is complete."
}

## Engine routing (from \`.aios/config.yaml\`)

- Resolved engine for the active agent: **${engineForNext.engineId}**${engineForNext.usedFallback ? " _(fallback to \`default\`)_" : ""}

## Inputs / outputs (from workflow step)

${
  active
    ? `- Inputs: ${(active.inputs ?? []).map((p) => `\`${p}\``).join(", ") || "(none listed)"}
- Outputs: ${(active.outputs ?? []).map((p) => `\`${p}\``).join(", ") || "(none listed)"}`
    : "- (n/a)"
}

## Blockers

${
  ctx.state.blocked
    ? "- State is marked **blocked** — unblock before relying on automation."
    : gatePreview.passed || !active
      ? "- No artifact gate failure detected for the active step (or no active gate)."
      : "- Gate checks failing — run the responsible agent, then re-check with \`aios next\`."
}

## Recommended next commands

${
  active
    ? gatePreview.passed
      ? `- \`aios approve --project ${ctx.projectId} --gate ${active.gate}\` (if you accept the gate)`
      : `- \`aios run --project ${ctx.projectId} --agent ${active.agent}\` (engine: **${engineForNext.engineId}**)`
    : `- \`aios status --project ${ctx.projectId}\` and pick tasks from \`backlog/tasks.yaml\``
}

_Generated by **delivery-manager** at ${new Date().toISOString()}._
`;

  await writeMarkdown(join(ctx.projectRoot, statusPath), statusBody);

  const shortBody = `# Delivery summary — ${ctx.projectId}

See **${statusPath}** for the full operational status (engines, gates, blockers).

_Last update: ${new Date().toISOString()}._
`;
  await writeMarkdown(join(ctx.projectRoot, summaryPath), shortBody);

  return {
    agentId: "delivery-manager",
    success: true,
    message: `Wrote ${statusPath} and ${summaryPath}`,
    artifactsWritten: [statusPath, summaryPath],
  };
}
