import { writeMarkdown, writeYaml } from "@aios-celx/artifact-manager";
import type { AgentResult } from "@aios-celx/shared";
import { join } from "node:path";
import type { AgentExecutionContext } from "../context.js";

const epicsDoc = {
  epics: [
    {
      id: "EPIC-1",
      title: "Product foundation",
      goal: "Establish PRD, backlog structure, and initial delivery slice.",
      status: "draft",
    },
  ],
};

const storiesDoc = {
  stories: [
    {
      id: "STORY-1",
      epicId: "EPIC-1",
      title: "Publish initial PRD",
      acceptance: ["PRD contains summary and goals", "Backlog files are populated"],
      status: "draft",
    },
  ],
};

const tasksDoc = {
  tasks: [
    {
      id: "TASK-1",
      storyId: "STORY-1",
      title: "Fill PRD and backlog YAML with mock content",
      description: "Ensure backlog YAML validates and contains at least one executable task for the engineer agent.",
      type: "implementation",
      status: "todo",
      files: ["backlog/tasks.yaml", "docs/prd.md"],
      acceptanceCriteria: [
        "tasks.yaml parses with Task schema",
        "At least one task row exists with id and storyId",
      ],
      notes: "Used by Bloco 4.2 engineer mock (run:task).",
    },
  ],
};

export async function runProductManager(ctx: AgentExecutionContext): Promise<AgentResult> {
  const discovery = ctx.files["docs/discovery.md"] ?? "";

  const prdBody = `# Product Requirements — ${ctx.projectId}

## Summary

Mock PRD produced after discovery. The product should deliver user value described in discovery while respecting stated constraints.

_Discovery signal (excerpt):_
${discovery.split("\n").slice(0, 8).join("\n")}

## Goals

1. Ship a thin vertical slice that proves the core workflow.
2. Keep specs and backlog traceable (epic → story → task).

## User stories (high level)

- As a team member, I want a single source of truth for scope so that execution stays aligned.

## Functional requirements

- FR-001: CLI-managed projects must persist artifacts under \`docs/\` and \`backlog/\`.

## Non-functional requirements

- Performance: interactive CLI operations complete quickly on local disk.
- Security: no secrets committed in mock artifacts.

_Mock output generated by agent **product-manager** at ${new Date().toISOString()}._
`;

  const artifacts: string[] = [];
  const prdPath = "docs/prd.md";
  await writeMarkdown(join(ctx.projectRoot, prdPath), prdBody);
  artifacts.push(prdPath);

  for (const [rel, data] of [
    ["backlog/epics.yaml", epicsDoc],
    ["backlog/stories.yaml", storiesDoc],
    ["backlog/tasks.yaml", tasksDoc],
  ] as const) {
    await writeYaml(join(ctx.projectRoot, rel), data);
    artifacts.push(rel);
  }

  return {
    agentId: "product-manager",
    success: true,
    message: "Updated PRD and backlog YAML files.",
    artifactsWritten: artifacts,
  };
}
