import { writeMarkdown } from "@aios-celx/artifact-manager";
import type { AgentResult } from "@aios-celx/shared";
import { join } from "node:path";
import type { AgentExecutionContext } from "../context.js";

export async function runSoftwareArchitect(ctx: AgentExecutionContext): Promise<AgentResult> {
  const discovery = ctx.files["docs/discovery.md"] ?? "";
  const prd = ctx.files["docs/prd.md"] ?? "";
  const stories = ctx.files["backlog/stories.yaml"] ?? "";

  const archBody = `# Architecture — ${ctx.projectId}

## Context

The system is composed of a monorepo (\`aios-celx\`) orchestrating managed projects under \`projects/\`.
Each project stores human- and agent-generated artifacts on disk.

_Signals_

**Discovery excerpt**

\`\`\`
${discovery.split("\n").slice(0, 8).join("\n")}
\`\`\`

**PRD excerpt**

\`\`\`
${prd.split("\n").slice(0, 8).join("\n")}
\`\`\`

## Components

| Component | Responsibility | Notes |
|-----------|----------------|-------|
| apps/cli | Operator entrypoint | Invokes workflow + agents |
| workflow-engine | Steps & gates | YAML-defined delivery flow |
| agent-runtime | Mock agents | Writes real files |

## Data

- Primary artifacts: Markdown + YAML under each project's \`docs/\` and \`backlog/\`.

_Mock output generated by agent **software-architect** at ${new Date().toISOString()}._
`;

  const apiBody = `# API contracts — ${ctx.projectId}

## Conventions

- Base URL: \`https://api.example.local\`
- Versioning: \`/v1\`
- Errors: \`{ "error": { "code", "message" } }\`

## Endpoints

### Health

- \`GET /v1/health\` — returns \`{ "ok": true }\`

### Resources (illustrative)

- \`GET /v1/resources\`
- \`POST /v1/resources\`

_Stories input (excerpt)_

\`\`\`
${stories.split("\n").slice(0, 14).join("\n")}
\`\`\`

_Mock output generated by agent **software-architect** at ${new Date().toISOString()}._
`;

  const archPath = "docs/architecture.md";
  const apiPath = "docs/api-contracts.md";
  await writeMarkdown(join(ctx.projectRoot, archPath), archBody);
  await writeMarkdown(join(ctx.projectRoot, apiPath), apiBody);

  return {
    agentId: "software-architect",
    success: true,
    message: "Wrote architecture and API contract drafts.",
    artifactsWritten: [archPath, apiPath],
  };
}
