import { ensureDir, writeJson, writeMarkdown } from "@aios-celx/artifact-manager";
import { resolveAgentContext } from "@aios-celx/context-resolver";
import {
  findTaskById,
  loadStories,
  loadTasks,
  saveTasks,
  syncStoryStatusFromTasks,
  updateTaskStatus,
} from "@aios-celx/backlog-manager";
import { loadProjectConfig } from "@aios-celx/project-manager";
import type { QAReport, QAStatus, Task } from "@aios-celx/shared";
import {
  deriveTaskStatusAfterQa,
  QAReportSchema,
} from "@aios-celx/shared";
import { readState, updateState } from "@aios-celx/state-manager";
import { loadWorkflowForConfig } from "@aios-celx/workflow-engine";
import { join } from "node:path";
import { appendExecutionLogLine } from "./project-logs.js";

export type QaTaskResult = {
  ok: boolean;
  taskId: string;
  reportPath: string;
  jsonPath: string;
  status: QAStatus;
  message: string;
};

function safePathSegment(id: string): string {
  return id.replace(/[^a-zA-Z0-9._-]/g, "-");
}

function buildMockQaReport(task: Task, implText: string, storyTitle: string | undefined): QAReport {
  const notes = (task.notes ?? "").toLowerCase();
  const idLower = task.id.toLowerCase();
  let status: QAStatus = "approved";
  const findings: QAReport["findings"] = [];

  if (notes.includes("qa:block") || idLower.includes("qa-block")) {
    status = "blocked";
    findings.push({
      type: "process",
      severity: "critical",
      title: "Blocked (mock)",
      description: "Simulated blocker from task id or notes (qa:block).",
      relatedTaskId: task.id,
      relatedStoryId: task.storyId,
    });
  } else if (notes.includes("qa:changes") || idLower.includes("qa-changes")) {
    status = "changes_requested";
    findings.push({
      type: "quality",
      severity: "medium",
      title: "Changes requested (mock)",
      description: "Simulated review feedback from task id or notes (qa:changes).",
      relatedTaskId: task.id,
      relatedStoryId: task.storyId,
    });
  } else if (implText.length < 80) {
    status = "changes_requested";
    findings.push({
      type: "documentation",
      severity: "low",
      title: "Thin implementation report",
      description: "Implementation report seems too short for confident sign-off.",
      relatedTaskId: task.id,
      relatedStoryId: task.storyId,
    });
  }

  const criteria = [
    "architecture.md present / readable",
    "api-contracts.md present / readable",
    "Implementation report exists",
    "Acceptance criteria reviewed",
  ];
  const failed = status === "approved" ? 0 : Math.min(findings.length || 1, criteria.length);
  const passed = criteria.length - failed;

  return QAReportSchema.parse({
    taskId: task.id,
    storyId: task.storyId,
    status,
    findings,
    summary: {
      criteriaChecked: criteria,
      passedCount: Math.max(0, passed),
      failedCount: Math.min(criteria.length, failed),
    },
    recommendation:
      status === "approved"
        ? "Proceed to merge or next task."
        : status === "blocked"
          ? "Resolve blockers before re-running QA."
          : "Address findings and re-run engineer + QA.",
    generatedAt: new Date().toISOString(),
  });
}

function renderQaMarkdown(report: QAReport, storyTitle: string | undefined): string {
  const findings =
    report.findings.length === 0
      ? "_No findings._"
      : report.findings
          .map(
            (f) =>
              `### ${f.title} (${f.severity})\n\n- **Type:** ${f.type}\n- ${f.description}`,
          )
          .join("\n\n");

  return `# QA report — ${report.taskId}

## Summary

| Field | Value |
|-------|--------|
| **Story** | ${report.storyId ?? "—"} (${storyTitle ?? "n/a"}) |
| **Generated** | ${report.generatedAt} |

**Final status**: \`${report.status}\`

**Criteria checked:** ${report.summary.criteriaChecked.join(", ")}

**Validation:** ${report.summary.passedCount} passed, ${report.summary.failedCount} failed.

## Findings

${findings}

## Recommendation

${report.recommendation}

---
_Generated by **qa-reviewer** (mock) — Bloco 4.3_
`;
}

export async function runQaTask(options: {
  projectsRoot: string;
  projectId: string;
  taskId: string;
}): Promise<QaTaskResult> {
  const { projectsRoot, projectId, taskId } = options;
  const projectRoot = join(projectsRoot, projectId);

  const config = await loadProjectConfig(projectsRoot, projectId);
  let tasksDoc = await loadTasks(projectRoot);
  const task = findTaskById(tasksDoc, taskId);
  if (!task) {
    return {
      ok: false,
      taskId,
      reportPath: "",
      jsonPath: "",
      status: "blocked",
      message: `Task not found: ${taskId}`,
    };
  }

  const safe = safePathSegment(taskId);
  const relImpl = `docs/execution/${safe}-implementation.md`;

  await appendExecutionLogLine(projectRoot, {
    type: "qa.task.start",
    projectId,
    taskId,
  });

  await updateState(projectsRoot, projectId, {
    currentTaskId: taskId,
    activeStoryId: task.storyId,
    lastExecutionType: "qa-task",
  });

  const state = await readState(projectsRoot, projectId);
  const workflow = await loadWorkflowForConfig(config);
  const resolved = await resolveAgentContext({
    projectsRoot,
    projectId,
    agentId: "qa-reviewer",
    taskId,
    storyId: task.storyId,
    state,
    workflow,
    fallbackReadPaths: [],
  });

  const implText = resolved.files[relImpl];
  if (implText === undefined) {
    return {
      ok: false,
      taskId,
      reportPath: "",
      jsonPath: "",
      status: "blocked",
      message: `Implementation report missing: ${relImpl}. Run \`aios run:task\` first.`,
    };
  }

  const archText = resolved.files["docs/architecture.md"] ?? "(missing)";
  const apiText = resolved.files["docs/api-contracts.md"] ?? "(missing)";
  const storiesDoc = await loadStories(projectRoot);
  const story = storiesDoc.stories.find((s) => s.id === task.storyId);

  const report = buildMockQaReport(task, implText, story?.title);
  const relMd = `qa/reports/${safe}-qa-report.md`;
  const relJson = `qa/reports/${safe}-qa-report.json`;
  await ensureDir(join(projectRoot, "qa", "reports"));

  const mdBody = `${renderQaMarkdown(report, story?.title)}

## Evidence read (excerpts)

### Architecture (first lines)

\`\`\`
${archText.split("\n").slice(0, 20).join("\n")}
\`\`\`

### API contracts (first lines)

\`\`\`
${apiText.split("\n").slice(0, 20).join("\n")}
\`\`\`

### Implementation report (first lines)

\`\`\`
${implText.split("\n").slice(0, 25).join("\n")}
\`\`\`
`;

  await writeMarkdown(join(projectRoot, relMd), mdBody);
  await writeJson(join(projectRoot, relJson), report);

  const nextStatus = deriveTaskStatusAfterQa(report.status);
  tasksDoc = updateTaskStatus(await loadTasks(projectRoot), taskId, nextStatus);
  await saveTasks(projectRoot, tasksDoc);
  await syncStoryStatusFromTasks(projectRoot, task.storyId);

  await appendExecutionLogLine(projectRoot, {
    type: "qa.task.done",
    projectId,
    taskId,
    qaStatus: report.status,
    taskStatus: nextStatus,
    report: relMd,
  });

  return {
    ok: true,
    taskId,
    reportPath: relMd,
    jsonPath: relJson,
    status: report.status,
    message: `QA ${report.status}; task → ${nextStatus}. Wrote ${relMd}`,
  };
}
