import { ensureDir, writeMarkdown } from "@aios-celx/artifact-manager";
import {
  listTasksByStoryId,
  loadStories,
  loadTasks,
  sortTasksById,
  syncStoryStatusFromTasks,
} from "@aios-celx/backlog-manager";
import { loadProjectConfig } from "@aios-celx/project-manager";
import { updateState } from "@aios-celx/state-manager";
import { join } from "node:path";
import { appendExecutionLogLine } from "./project-logs.js";
import { runEngineerTask } from "./engineer-task-runner.js";
import { runQaTask } from "./qa-task-runner.js";

function safePathSegment(id: string): string {
  return id.replace(/[^a-zA-Z0-9._-]/g, "-");
}

export type StoryTaskStepResult = {
  taskId: string;
  engineer?: { ok: boolean; message: string; reportPath?: string };
  qa?: { ok: boolean; message: string; status?: string; reportPath?: string };
};

export type StoryExecutionResult = {
  ok: boolean;
  storyId: string;
  reportPath: string;
  message: string;
  tasksPlanned: string[];
  steps: StoryTaskStepResult[];
};

export async function runStoryExecution(options: {
  projectsRoot: string;
  projectId: string;
  storyId: string;
  withQa: boolean;
}): Promise<StoryExecutionResult> {
  const { projectsRoot, projectId, storyId, withQa } = options;
  const projectRoot = join(projectsRoot, projectId);

  await loadProjectConfig(projectsRoot, projectId);
  const storiesDoc = await loadStories(projectRoot);
  const story = storiesDoc.stories.find((s) => s.id === storyId);
  if (!story) {
    return {
      ok: false,
      storyId,
      reportPath: "",
      message: `Story not found: ${storyId}`,
      tasksPlanned: [],
      steps: [],
    };
  }

  const tasksDoc = await loadTasks(projectRoot);
  const tasks = sortTasksById(listTasksByStoryId(tasksDoc, storyId));
  const tasksPlanned = tasks.map((t) => t.id);
  if (tasks.length === 0) {
    return {
      ok: false,
      storyId,
      reportPath: "",
      message: `No tasks linked to story ${storyId} in backlog/tasks.yaml`,
      tasksPlanned: [],
      steps: [],
    };
  }

  await appendExecutionLogLine(projectRoot, {
    type: "story.execution.start",
    projectId,
    storyId,
    withQa,
    taskIds: tasksPlanned,
  });

  await updateState(projectsRoot, projectId, {
    activeStoryId: storyId,
    lastExecutionType: "story-run",
  });

  const steps: StoryTaskStepResult[] = [];
  let allOk = true;

  for (const task of tasks) {
    const step: StoryTaskStepResult = { taskId: task.id };

    const eng = await runEngineerTask({
      projectsRoot,
      projectId,
      taskId: task.id,
    });
    step.engineer = {
      ok: eng.ok,
      message: eng.message,
      reportPath: eng.reportPath || undefined,
    };
    if (!eng.ok) {
      allOk = false;
      steps.push(step);
      break;
    }

    if (withQa) {
      const qa = await runQaTask({
        projectsRoot,
        projectId,
        taskId: task.id,
      });
      step.qa = {
        ok: qa.ok,
        message: qa.message,
        status: qa.status,
        reportPath: qa.reportPath || undefined,
      };
      if (!qa.ok) {
        allOk = false;
      }
    }

    steps.push(step);

    const latestTasks = await loadTasks(projectRoot);
    const blocked = latestTasks.tasks.find((x) => x.id === task.id)?.status === "blocked";
    if (blocked) {
      allOk = false;
      break;
    }
  }

  await syncStoryStatusFromTasks(projectRoot, storyId);

  const safe = safePathSegment(storyId);
  const relReport = `docs/execution/${safe}-execution.md`;
  await ensureDir(join(projectRoot, "docs", "execution"));

  const finalTasks = await loadTasks(projectRoot);
  const finalForStory = sortTasksById(listTasksByStoryId(finalTasks, storyId));

  const body = `# Story execution report — ${storyId}

## Story

| Field | Value |
|-------|--------|
| **Title** | ${story.title} |
| **With QA** | ${withQa ? "yes" : "no"} |
| **Generated** | ${new Date().toISOString()} |

## Tasks (plan)

${tasksPlanned.map((id) => `- \`${id}\``).join("\n")}

## Tasks (final status)

${finalForStory.map((t) => `- **${t.id}** — \`${t.status}\` — ${t.title}`).join("\n")}

## Steps

${steps
  .map((s) => {
    const lines = [`### ${s.taskId}`];
    if (s.engineer) {
      lines.push(`- **Engineer:** ${s.engineer.ok ? "ok" : "fail"} — ${s.engineer.message}`);
    }
    if (s.qa) {
      lines.push(
        `- **QA:** ${s.qa.ok ? "ok" : "fail"} — ${s.qa.status ?? ""} — ${s.qa.message}`,
      );
    }
    return lines.join("\n");
  })
  .join("\n\n")}

## Pendências / notas

- Execução **sequencial** (Bloco 4.4); sem paralelismo.
- Se QA pedir mudanças, task volta para \`in_progress\`; reexecute \`run:task\` / \`run:story\` conforme necessário.

---
_Generated by **story execution** (mock)_
`;

  await writeMarkdown(join(projectRoot, relReport), body);

  await appendExecutionLogLine(projectRoot, {
    type: "story.execution.done",
    projectId,
    storyId,
    ok: allOk,
    report: relReport,
    withQa,
  });

  return {
    ok: allOk,
    storyId,
    reportPath: relReport,
    message: allOk
      ? `Story run finished; wrote ${relReport}`
      : `Story run finished with issues; see ${relReport}`,
    tasksPlanned,
    steps,
  };
}
